version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: banco_db
      MYSQL_ROOT_PASSWORD: 154413711
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p154413711 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: tp2_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banco_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 154413711
    depends_on:
      db:
        condition: service_healthy